/**
 * langs.test.mjs — 语言注册表测试（--lang / STUDY_LANG 的公共依赖）。
 *
 * 运行：node --test apps/quiz-app/scripts/lib/langs.test.mjs
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { SUPPORTED_LANGS, DEFAULT_LANG, resolveLang, langConf } from './langs.mjs';
import { wrapLessonHTML, buildOutlinePrompt } from './teach-utils.mjs';
import { wrapClusterHTML, wrapIndexHTML, buildClusterPrompt, buildClusterGrillPrompt } from './grill-utils.mjs';
import { buildPodcastPrompt, renderTranscript } from './podcast-utils.mjs';

// ── 注册表结构 ────────────────────────────────────────────

test('SUPPORTED_LANGS 覆盖 zh/en/es/ru 四语', () => {
  assert.deepEqual(Object.keys(SUPPORTED_LANGS), ['zh', 'en', 'es', 'ru']);
});

test('每语配置字段齐全（code/htmlLang/native/directive/ui）', () => {
  const uiKeys = [
    'prevLesson', 'nextLesson', 'autoGenerated', 'lessonFooter',
    'wrongTitle', 'wrongMetaIds', 'backToWrongIndex', 'relatedLessons', 'wrongFooter',
    'indexTitle', 'indexAuto', 'backToCourseHome', 'indexLead', 'indexH2',
    'indexCount', 'indexEmpty', 'indexFooter', 'femaleHost', 'maleHost',
  ];
  for (const conf of Object.values(SUPPORTED_LANGS)) {
    assert.equal(conf.code.length, 2);
    assert.ok(conf.htmlLang);
    assert.ok(conf.native);
    assert.ok(conf.directive.length > 5);
    for (const k of uiKeys) assert.ok(conf.ui[k], `${conf.code}.ui.${k} 缺失`);
  }
});

test('indexCount 占位符 {n} 四语都在', () => {
  for (const conf of Object.values(SUPPORTED_LANGS)) {
    assert.match(conf.ui.indexCount, /\{n\}/);
  }
});

// ── resolveLang ───────────────────────────────────────────

test('resolveLang: 默认 zh', () => {
  assert.equal(resolveLang(undefined, undefined), DEFAULT_LANG);
});

test('resolveLang: flag 优先于环境变量', () => {
  assert.equal(resolveLang('ru', 'es'), 'ru');
});

test('resolveLang: 无 flag 时用环境变量', () => {
  assert.equal(resolveLang(undefined, 'es'), 'es');
});

test('resolveLang: 非法值抛错并列出支持语言', () => {
  assert.throws(() => resolveLang('fr', undefined), /fr/);
  assert.throws(() => resolveLang('fr', undefined), /zh \/ en \/ es \/ ru/);
});

test('langConf: 未知 code 兜底 zh', () => {
  assert.equal(langConf('fr').code, 'zh');
  assert.equal(langConf(undefined).code, 'zh');
});

// ── wrap 模板按语言渲染 ───────────────────────────────────

test('wrapLessonHTML: lang=en 时 html lang 与导航文案切换', () => {
  const html = wrapLessonHTML({
    mainContent: '<p>hello</p>', title: 'T', lessonNum: 2, total: 3,
    prevFile: '0001-a.html', nextFile: '0003-c.html', nextTitle: 'C', lang: 'en',
  });
  assert.match(html, /<html lang="en">/);
  assert.match(html, /← Previous lesson/);
  assert.match(html, /Next lesson: <a href="0003-c\.html">C<\/a>/);
  assert.doesNotMatch(html, /上一课/);
});

test('wrapLessonHTML: 不传 lang 保持 zh 默认（向后兼容）', () => {
  const html = wrapLessonHTML({ mainContent: 'x', title: 'T', lessonNum: 1, total: 1 });
  assert.match(html, /<html lang="zh-CN">/);
});

test('wrapClusterHTML / wrapIndexHTML: lang=es 时切换固定文案', () => {
  const c = wrapClusterHTML({ mainContent: 'x', topic: 'git', ids: ['G-1'], lang: 'es' });
  assert.match(c, /<html lang="es">/);
  assert.match(c, /Análisis de erróneas · git/);
  assert.doesNotMatch(c, /错题精讲/);

  const i = wrapIndexHTML([{ topic: 'git', file: 'cluster-01-git.html', count: 2 }], 'dev-intro', 'es');
  assert.match(i, /<html lang="es">/);
  assert.match(i, /Centro de erróneas/);
  assert.match(i, /2 preguntas/); // indexCount 的 {n} 被替换
  assert.doesNotMatch(i, /题</);
});

// ── prompt 带语言指令 ─────────────────────────────────────

test('buildOutlinePrompt: lang=ru 时 system 含俄语指令', () => {
  const p = buildOutlinePrompt({ mission: 'x', audience: 'y', depth: 'beginner' }, 3, 'ru');
  assert.match(p.system, /русском языке/);
});

test('buildClusterPrompt / buildClusterGrillPrompt: lang=en 时含英语指令', () => {
  const wrong = [{ id: 'G-1', record: { streak: 0, selected: ['A'], wrongCount: 1 }, question: { id: 'G-1', question: 'q', options: { A: 'a' }, answer: ['B'] } }];
  assert.match(buildClusterPrompt(wrong, 5, 'en').system, /Write all content in English/);
  assert.match(
    buildClusterGrillPrompt({ topic: 't', ids: ['G-1'] }, wrong, [], 'en').system,
    /Write all content in English/,
  );
});

test('buildPodcastPrompt: lang=es 时含西语指令', () => {
  const p = buildPodcastPrompt('素材', '标题', { lang: 'es' });
  assert.match(p.system, /español/);
});

test('renderTranscript: lang=ru 时主播称呼本地化', () => {
  const md = renderTranscript(
    [{ speaker: 'female', text: 'Привет!' }, { speaker: 'male', text: 'Привет.' }],
    'Тест', 'ru',
  );
  assert.match(md, /\*\*👩 Ведущая\*\*：Привет!/);
  assert.match(md, /\*\*👨 Ведущий\*\*：Привет\./);
  assert.doesNotMatch(md, /女主播/);
});
