/**
 * langs.mjs — AI CLI 的输出语言注册表（teach / grill / podcast 共用）。
 *
 * 设计原则：
 * - `--lang <code>` 或环境变量 STUDY_LANG 选语言，默认 zh；
 * - --lang 只控制**生成内容**的语言（课程正文、错题精讲、播客对白），
 *   CLI 自身的日志/报错仍用中文（操作者是仓库维护者，与 README 约定一致）；
 * - prompt 指令（directive）用目标语言本身写——对 LLM 的约束力比"请用英语写"更强；
 * - wrap 模板里的少量固定文案（上一课/下一课、页脚说明、主播名）按语言给全，
 *   避免生成 en 内容却嵌中文导航。
 *
 * 前端 UI 的多语言在 apps/quiz-app/src/i18n/（另一套词典），两边语言集保持同步。
 */

export const SUPPORTED_LANGS = {
  zh: {
    code: 'zh',
    htmlLang: 'zh-CN',       // <html lang> 属性值
    native: '中文',           // CLI 启动横幅显示用
    directive: '全文用简体中文撰写（技术名词和代码可保留英文）。',
    ui: {
      prevLesson: '← 上一课',
      nextLesson: '下一课：',
      autoGenerated: 'ai-study-kit 自动生成课程',
      lessonFooter:
        '💡 本课由 ai-study-kit 的 <code>teach-generate.mjs</code> 自动生成。如有不清楚的地方，可以让 AI 助手进一步讲解。',
      wrongTitle: '错题精讲',
      wrongMetaIds: '对应题目：',
      backToWrongIndex: '← 返回错题中心',
      relatedLessons: '相关课程：',
      wrongFooter:
        '💡 本精讲由 ai-study-kit 的 <code>grill-wrong.mjs</code> 自动生成。如有不清楚，可以让 AI 助手进一步讲解。',
      indexTitle: '错题学习中心',
      indexAuto: 'ai-study-kit 自动生成',
      backToCourseHome: '← 返回课程主页',
      indexLead: '由 <code>grill-wrong.mjs</code> 从你的答题进度自动聚类生成。每个簇是一个高频错点的深度展开。',
      indexH2: '🔥 易错点精讲',
      indexCount: '{n} 题',
      indexEmpty: '（暂无错题——多刷几道题后再来跑 grill-wrong.mjs）',
      indexFooter: '💡 本页由 ai-study-kit 的 <code>grill-wrong.mjs</code> 自动生成。',
      femaleHost: '👩 女主播',
      maleHost: '👨 男主播',
    },
  },
  en: {
    code: 'en',
    htmlLang: 'en',
    native: 'English',
    directive: 'Write all content in English (keep technical terms and code as-is).',
    ui: {
      prevLesson: '← Previous lesson',
      nextLesson: 'Next lesson: ',
      autoGenerated: 'auto-generated course by ai-study-kit',
      lessonFooter:
        '💡 This lesson was auto-generated by ai-study-kit’s <code>teach-generate.mjs</code>. Ask your AI assistant to elaborate on anything unclear.',
      wrongTitle: 'Wrong-Question Deep Dive',
      wrongMetaIds: 'Questions: ',
      backToWrongIndex: '← Back to wrong-question hub',
      relatedLessons: 'Related lessons: ',
      wrongFooter:
        '💡 This deep dive was auto-generated by ai-study-kit’s <code>grill-wrong.mjs</code>. Ask your AI assistant to elaborate on anything unclear.',
      indexTitle: 'Wrong-Question Hub',
      indexAuto: 'auto-generated by ai-study-kit',
      backToCourseHome: '← Back to course home',
      indexLead: 'Clustered automatically from your quiz progress by <code>grill-wrong.mjs</code>. Each cluster is a deep dive into one frequent mistake.',
      indexH2: '🔥 Deep dives',
      indexCount: '{n} questions',
      indexEmpty: '(No wrong questions yet — answer more questions, then run grill-wrong.mjs again)',
      indexFooter: '💡 This page was auto-generated by ai-study-kit’s <code>grill-wrong.mjs</code>.',
      femaleHost: '👩 Host',
      maleHost: '👨 Host',
    },
  },
  es: {
    code: 'es',
    htmlLang: 'es',
    native: 'Español',
    directive: 'Escribe todo el contenido en español (los términos técnicos y el código pueden quedarse en inglés).',
    ui: {
      prevLesson: '← Lección anterior',
      nextLesson: 'Siguiente lección: ',
      autoGenerated: 'curso generado automáticamente por ai-study-kit',
      lessonFooter:
        '💡 Esta lección fue generada automáticamente por <code>teach-generate.mjs</code> de ai-study-kit. Pide a tu asistente de IA que amplíe lo que no quede claro.',
      wrongTitle: 'Análisis de erróneas',
      wrongMetaIds: 'Preguntas: ',
      backToWrongIndex: '← Volver al centro de erróneas',
      relatedLessons: 'Lecciones relacionadas: ',
      wrongFooter:
        '💡 Este análisis fue generado automáticamente por <code>grill-wrong.mjs</code> de ai-study-kit. Pide a tu asistente de IA que amplíe lo que no quede claro.',
      indexTitle: 'Centro de erróneas',
      indexAuto: 'generado automáticamente por ai-study-kit',
      backToCourseHome: '← Volver al inicio del curso',
      indexLead: 'Agrupado automáticamente desde tu progreso por <code>grill-wrong.mjs</code>. Cada clúster es un análisis profundo de un error frecuente.',
      indexH2: '🔥 Análisis de errores',
      indexCount: '{n} preguntas',
      indexEmpty: '(Aún no hay erróneas — responde más preguntas y vuelve a ejecutar grill-wrong.mjs)',
      indexFooter: '💡 Esta página fue generada automáticamente por <code>grill-wrong.mjs</code> de ai-study-kit.',
      femaleHost: '👩 Locutora',
      maleHost: '👨 Locutor',
    },
  },
  ru: {
    code: 'ru',
    htmlLang: 'ru',
    native: 'Русский',
    directive: 'Пишите весь контент на русском языке (технические термины и код можно оставить на английском).',
    ui: {
      prevLesson: '← Предыдущий урок',
      nextLesson: 'Следующий урок: ',
      autoGenerated: 'курс создан автоматически ai-study-kit',
      lessonFooter:
        '💡 Этот урок создан автоматически <code>teach-generate.mjs</code> из ai-study-kit. Попросите ИИ-ассистента подробнее объяснить неясные места.',
      wrongTitle: 'Разбор ошибок',
      wrongMetaIds: 'Вопросы: ',
      backToWrongIndex: '← К списку ошибок',
      relatedLessons: 'Связанные уроки: ',
      wrongFooter:
        '💡 Этот разбор создан автоматически <code>grill-wrong.mjs</code> из ai-study-kit. Попросите ИИ-ассистента подробнее объяснить неясные места.',
      indexTitle: 'Центр ошибок',
      indexAuto: 'создано автоматически ai-study-kit',
      backToCourseHome: '← На главную курса',
      indexLead: 'Сгруппировано автоматически из вашего прогресса скриптом <code>grill-wrong.mjs</code>. Каждый кластер — глубокий разбор одной частой ошибки.',
      indexH2: '🔥 Разборы ошибок',
      indexCount: '{n} вопр.',
      indexEmpty: '(Ошибок пока нет — решите больше вопросов и снова запустите grill-wrong.mjs)',
      indexFooter: '💡 Эта страница создана автоматически <code>grill-wrong.mjs</code> из ai-study-kit.',
      femaleHost: '👩 Ведущая',
      maleHost: '👨 Ведущий',
    },
  },
};

export const DEFAULT_LANG = 'zh';

/**
 * 解析语言参数：--lang 值优先，其次 STUDY_LANG 环境变量，默认 zh。
 * 非法值抛错（由各 CLI 的 main().catch 统一打印）。
 * @param {string | null | undefined} flagValue  --lang 参数值
 * @param {string | undefined} envValue  process.env.STUDY_LANG
 * @returns {string} 语言 code
 */
export function resolveLang(flagValue, envValue) {
  const raw = flagValue ?? envValue ?? DEFAULT_LANG;
  if (!SUPPORTED_LANGS[raw]) {
    throw new Error(`不支持的语言：${raw}（支持：${Object.keys(SUPPORTED_LANGS).join(' / ')}）`);
  }
  return raw;
}

/** 取语言配置；未知 code 兜底 zh（防御，正常路径都应经 resolveLang 校验）。 */
export function langConf(lang) {
  return SUPPORTED_LANGS[lang] ?? SUPPORTED_LANGS[DEFAULT_LANG];
}
