/**
 * teach-utils.mjs — teach-generate.mjs 的纯函数工具集（可单测）。
 *
 * 把不调 LLM 的逻辑拎出来：slugify、escapeHTML、wrapLessonHTML、
 * 校验 course-spec、构建 prompt 等。
 */
import { langConf } from './langs.mjs';

/** HTML 转义。 */
export function escapeHTML(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }[c]));
}

/**
 * 把中文/英文混合的标题转成文件名 slug。
 * 保留中文（文件系统支持），空格/点/·转 -，去特殊符号，限长 40。
 */
export function slugify(s) {
  return s
    .trim()
    .toLowerCase()
    .replace(/[\s\·\.]+/g, '-')
    .replace(/[^\p{L}\p{N}-]/gu, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40)
    || 'lesson';
}

/**
 * 校验 course-spec 必填字段。
 * @param {object} spec
 * @returns {{ ok: true, spec: object } | { ok: false, missing: string[] }}
 */
export function validateCourseSpec(spec) {
  const required = ['theme', 'mission', 'audience', 'depth'];
  const missing = required.filter((f) => !spec[f]);
  if (missing.length > 0) return { ok: false, missing };
  const validDepths = ['beginner', 'intermediate', 'advanced'];
  if (!validDepths.includes(spec.depth)) {
    return { ok: false, missing: [`depth (must be one of: ${validDepths.join('/')})`] };
  }
  return { ok: true, spec };
}

/**
 * 解析 RESOURCES.md 的资源链接（宽容解析，teach 工作流约定每个主题维护一份）。
 * 认两种形态，只取带 URL 的行（无 URL 的行如 `man ls` 不产出链接）：
 *   - **标题**（说明）：https://url     ← 本仓库 RESOURCES.md 的实际写法
 *   - [标题](https://url)               ← 标准 markdown 链接
 */
export function parseResourcesMd(text) {
  if (!text) return [];
  const out = [];
  for (const m of text.matchAll(/^-+\s*\*\*(.+?)\*\*[^:：]*[:：]\s*(https?:\/\/\S+)\s*$/gm)) {
    out.push({ title: m[1].trim(), url: m[2].trim() });
  }
  for (const m of text.matchAll(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g)) {
    out.push({ title: m[1].trim(), url: m[2].trim() });
  }
  return out;
}

/**
 * course-spec.resources 与 RESOURCES.md 解析结果合并（URL 去重，spec 在前保序）。
 * 合并结果既进 LLM prompt（备课参考），也进课程页脚的出处回链块。
 */
export function mergeResources(specResources, mdResources) {
  const seen = new Set();
  const out = [];
  for (const r of [...(specResources || []), ...(mdResources || [])]) {
    if (!r || !r.title || !r.url || seen.has(r.url)) continue;
    seen.add(r.url);
    out.push({ title: r.title, url: r.url });
  }
  return out;
}

/**
 * 把 LLM 产的 <main> 内容包成完整 HTML 文档。
 * @param {object} params
 * @param {string} params.mainContent  LLM 返回的 <main>...</main> 内容（或纯正文）
 * @param {string} params.title        课程标题（已 escape）
 * @param {number} params.lessonNum    当前课次（1-based）
 * @param {number} params.total        总课数
 * @param {string} [params.prevFile]   上一课文件名（可选）
 * @param {string} [params.nextFile]   下一课文件名（可选）
 * @param {string} [params.nextTitle]  下一课标题（可选）
 * @param {string} [params.lang='zh']  输出语言（导航/页脚文案 + <html lang>）
 * @param {Array}  [params.sources]    出处回链（course-spec.resources 与 RESOURCES.md 合并结果；
 *                                     「以参考材料建概念」原则的产物面——每课页脚列权威来源）
 */
export function wrapLessonHTML({ mainContent, title, lessonNum, total, prevFile, nextFile, nextTitle, lang = 'zh', sources = [] }) {
  const conf = langConf(lang);
  const prevLink = prevFile
    ? `<a href="${prevFile}">${conf.ui.prevLesson}</a>　·　`
    : '';
  const nextLink = (nextFile && nextTitle)
    ? `　·　${conf.ui.nextLesson}<a href="${nextFile}">${escapeHTML(nextTitle)}</a>`
    : '';
  const sourcesBlock = sources.length
    ? `\n<aside class="sources"><p>📚 ${conf.ui.sources}：${sources
        .map((r) => `<a href="${escapeHTML(r.url)}" target="_blank" rel="noopener">${escapeHTML(r.title)}</a>`)
        .join(' · ')}</p></aside>\n`
    : '';
  return `<!DOCTYPE html>
<html lang="${conf.htmlLang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHTML(title)}</title>
<link rel="stylesheet" href="../assets/styles.css">
</head>
<body>
<main>
<h1>${escapeHTML(title)}</h1>
<p class="meta">${prevLink}${conf.ui.autoGenerated}${nextLink}</p>

${mainContent.trim()}
${sourcesBlock}
<footer>
<p>${conf.ui.lessonFooter}</p>
</footer>
</main>
</body>
</html>
`;
}

/**
 * 构建"生成大纲"的 LLM prompt。
 * 抽出便于单测 prompt 结构。
 * @param {object} spec
 * @param {number} lessonsCount
 * @param {string} [lang='zh']  大纲主题的输出语言
 */
export function buildOutlinePrompt(spec, lessonsCount, lang = 'zh') {
  const conf = langConf(lang);
  const resourcesBlock = (spec.resources || [])
    .map((r, i) => `  ${i + 1}. ${r.title}${r.url ? ` (${r.url})` : ''}`)
    .join('\n') || '  (无指定资源，请基于你的通用知识拆解)';
  return {
    system: `你是一位资深学习设计师。任务：把一个学习目标拆成 ${lessonsCount} 节课的递进大纲。

⚠️ **关键约束**：必须返回正好 ${lessonsCount} 个主题。不要多也不要少。如果你觉得 ${lessonsCount} 节太少，就把每节涵盖的内容做大（一节可以讲多个相关概念），但**总数必须是 ${lessonsCount}**。

输出语言约束：${conf.directive}

输出**严格 JSON**：{ "outline": ["课次1主题", "课次2主题", ...] }
数组长度必须等于 ${lessonsCount}。不要任何额外文字。`,
    user: `学习目标：${spec.mission}
受众：${spec.audience}
深度：${spec.depth}
可用资源：
${resourcesBlock}

请拆成正好 ${lessonsCount} 节课的大纲，每节主题用 4-12 个字描述（如"Hook 基础与 useState"）。
顺序从浅到深，前后节有逻辑衔接。

再次强调：数组长度必须是 ${lessonsCount}，不能多。`,
  };
}

/**
 * 构建"生成一课正文"的 LLM messages（v0.13 起可带参考材料正文块）。
 * 抽出便于单测 prompt 结构（dry-run 断言备课 prompt 含参考正文，不调 LLM）。
 * @param {object} params 与 teach-generate.generateLessonMain 同参
 * @param {string} [params.referenceTextBlock]  抓取的参考正文块（空串 = 无，退回纯 URL 清单）
 */
export function buildLessonPrompt({ spec, topic, lessonNum, total, outline, lang = 'zh', referenceTextBlock = '' }) {
  const conf = langConf(lang);
  const resourcesBlock = (spec.resources || [])
    .map((r) => `- ${r.title}${r.url ? ` (${r.url})` : ''}`)
    .join('\n') || '(无指定资源)';
  const outlineBlock = outline.map((t, i) => `  第 ${i + 1} 课：${t}`).join('\n');
  const referenceSection = referenceTextBlock
    ? `\n## 参考材料正文（抓取自上述链接，备课第一依据；材料未覆盖的内容才可用你的通用知识）\n${referenceTextBlock}\n`
    : '';
  return [
    {
      role: 'system',
      content: `你是一位优秀的讲师，擅长把复杂概念讲清楚。任务：写一节 HTML 课程内容。

## 输出语言
${conf.directive}

## 输出格式
**只返回 HTML 片段，不要 <main> 标签**（我会用模板包 <main>）。
不要包含 <!DOCTYPE>/<html>/<head>/<body>/<main>——只返回正文的 <h2>/<p>/<ul>/<table>/<div> 等。
第一行直接从 <h2> 开始（不要重复 <h1>，标题由模板负责）。

## 内容要求
- 围绕"${topic}"这个主题讲透
- 至少 3 个二级标题（<h2>），从概念到实践层层递进
- 重点用 <div class="callout"> 高亮（核心结论）
- 易错点用 <div class="callout callout-warn"> 高亮
- 实用技巧用 <div class="callout callout-tip"> 高亮
- 代码或命令用 <pre><code>...</code></pre> 包裹
- 对照/比较用 <div class="compare"><div><h4>A</h4><p>...</p></div><div><h4>B</h4><p>...</p></div></div>
- 表格用标准 <table><thead><tbody>
- 核心机制示意图：每课至少 1 张，用内联 <svg>（设 viewBox，style="width:100%;height:auto" 自适应）；节点 + 箭头表达流转/层次/对比，图大字少、只画机制不画装饰，图内文字用本课输出语言；禁止外链图片、禁止 emoji 拼贴
- 末尾加 <div class="quiz-anchor">对应考点关键词列表</div> 标注本课对应的核心考点（用于四对齐校验）
- 长度：800-1500 字之间（非中文按同等信息量折算）
- 风格：口语化、有具体例子、避免空洞术语堆砌

## 风格参考
- 读者：${spec.audience}
- 深度：${spec.depth}
- 引用资源用 <a href="...">资源名</a>，但不要堆砌外链

直接开始写正文 HTML 片段（从 <h2> 开始），不要任何前后解释。`,
    },
    {
      role: 'user',
      content: `学习目标（整门课）：${spec.mission}

本课在整门课的位置：
${outlineBlock}

当前要写的是第 ${lessonNum} 课：${topic}

可用资源：
${resourcesBlock}
${referenceSection}
请写第 ${lessonNum} 课（共 ${total} 课）的 HTML 正文片段。`,
    },
  ];
}

/**
 * 容错处理 LLM 返回的 outline：长度不匹配时取前 N 个或补齐。
 * @param {string[]} outline  LLM 返回的大纲
 * @param {number} expected   期望长度
 * @returns {string[]}  长度 === expected 的数组
 */
export function normalizeOutline(outline, expected) {
  if (!Array.isArray(outline)) {
    throw new Error(`outline 不是数组：${typeof outline}`);
  }
  const strs = outline.map(String);
  if (strs.length === expected) return strs;
  if (strs.length > expected) {
    // LLM 多产了，取前 N 个
    return strs.slice(0, expected);
  }
  // LLM 少产了，补齐占位
  while (strs.length < expected) {
    strs.push(`第 ${strs.length + 1} 课`);
  }
  return strs;
}
